### ISSUE TITLE
Recursive copy setting on registry

### ISSUE THREAD

**Issue by DanielSank** [maffoo/scalabrad#13]
To make copying not slow as molasses :-)

**Comment by maffoo** [comment]
This sounds like a great project for someone new to scala to implement :)

If you add the setting to the [Registry](https://github.com/labrad/scalabrad/blob/master/src/main/scala/org/labrad/registry/Registry.scala) class using the existing methods on `RegistryStore`, then this will work with all the existing backends (sqlite, binary file and delphi-formatted file) so you wouldn't need to write separate implementations for the various backing stores (we could optimize for the backing stores later if we really wanted). Note that the [api](https://github.com/labrad/scalabrad-web/blob/master/server/src/main/scala/org/labrad/browser/RegistryController.scala#L201) provided in scalabrad-web implements various high-level copy/rename/move operations for keys as well as directories so at least we insulate the client from having to do the recursion. But if those were implemented in the registry server instead, then the logic there in the web api could also be replaced by simple labrad calls.

**Comment by DanielSank** [comment]
> This sounds like a great project for someone new to scala to implement :)

I can't imagine who you you might be talking about. Is it @jwenner?

**Comment by DanielSank** [comment]
Closing this until such time as we find that the batched calls from the new registry editor don't fix the problem.
