### ISSUE TITLE
allow single quoted strings in manager's String To Data setting

### ISSUE THREAD

**Issue by joshm-3b6b58** [maffoo/scalabrad#15]
To be more like Delphi manager

**Comment by DanielSank** [comment]
Could you be more clear? Allow single quoted strings where?

**Comment by maffoo** [comment]
This is in the string format, e.g. what you type into the registry editor to update data. Currently, the scala manager accepts scala/java/c-style double-quoted strings only, wherease the delphi manager accepted delphi-style single-quoted strings. A nice option would be to accept either single or double-quotes, python-style (also continue to use backslash escaping like python and the rest of the world, not delphi-style # escapes).

**Comment by DanielSank** [comment]
So we're talking about the wire format?

**Comment by maffoo** [comment]
no, nothing to do with the wire format. we're talking about what the manager's `string_to_data` setting accepts.

**Comment by DanielSank** [comment]
Updated title to be more precise.

**Comment by ejeffrey** [comment]
Part of this should be documenting a canonical test representation of labrad data, and that should be what is implemented by string_to_data and data_to_string.
