### ISSUE TITLE
Do we need to require more documentation?

### ISSUE THREAD

**Issue by DanielSank** [maffoo/scalabrad#17]
It seems there are very few comments in Scala code. While I understand that the situation is quite different from python where we have to laboriously document even things like expected types, I would think documentation of intent could still be useful.

As a case study, I've been trying to understand the code in `Registry.scala`. Here's an excerpt

``` scala
    def changeDir(dir: Either[String, Seq[String]], create: Boolean = false): Seq[String] = {
    ...
    }
```

What is `dir`? Reading through the code one finds that it's the directory _relative to the current directory_ into which we navigate. This isn't obvious at all until you read the code and also the `_mkDir` code. I think we should do better.

Thoughts?

**Comment by maffoo** [comment]
Yes, we should document things better. Since I've been writing all this code myself, I haven't done a very good job of that, but I'm really glad to have at least one more set of eyes on it to keep me honest :)
