### ISSUE TITLE
How do I build and deploy the manager?

### ISSUE THREAD

**Issue by DanielSank** [maffoo/scalabrad#3]

**Comment by maffoo** [comment]
At the moment, we have the [sbt-pack](https://github.com/xerial/sbt-pack) extension set up in the build, so running `sbt packArchive` will produce a tarball in `target/scalabrad-<version>.tar.gz` which you can distribute. Inside the tarball, there are scripts to launch the manager on *nix and windows, e.g.:

```
> scalabrad-<version>/bin/labrad[.bat]
```
