### ISSUE TITLE
Server connect/disconnect notifications not working

### ISSUE THREAD

**Issue by ejeffrey** [maffoo/scalabrad#33]
It seems that clients are not getting notifications of new servers connected, and I have to manually call cxn.refresh().  This is with scalabrad-0.4.0 from bintray, so I think that it should be including the #29 fix.

**Comment by maffoo** [comment]
Are you talking about synchronous clients? I don't think we have ever had server connect/disconnect messages set up to trigger refresh in synchronous clients. I tried running the python test server, which logs when it gets server connect/disconnect messages, and I see them as expected when other servers connect and disconnect.

**Comment by ejeffrey** [comment]
Hmm... I thought that worked in the past, but apparently not.  Closing.

**Comment by maffoo** [comment]
Feel free to file an issue with pylabrad to add (or resurrect?) this feature; it would be nice to have.
