### ISSUE TITLE
Unable to connect from other computers

### ISSUE THREAD

**Issue by jwenner** [maffoo/scalabrad#36]
@maffoo, @ejeffrey: When I try to connect to a computer (rottmayer in the example below) running scalabrad-0.5.0 from bintray, I get a message "Expected STARTTLS". Is there something I should be doing (in which case documentation is needed) or is this a bug? Note that I'm running current pylabrad master. Also, this is the first time for running the scalabrad manager on rottmayer, so maybe there's some configuration stuff which needs to be done?

Full traceback as follows:

```
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]
Type "copyright", "credits" or "license" for more information.

IPython 2.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import labrad

In [2]: cxn=labrad.connect(host='rottmayer')
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-2-dd6249c2a6d2> in <module>()
----> 1 cxn=labrad.connect(host='rottmayer')

C:\Code\pylabrad\labrad\__init__.pyc in connect(host, port, name, **kw)
     26 def connect(host=constants.MANAGER_HOST, port=constants.MANAGER_PORT, na
me=None, **kw):
     27     """Create a client connection to the labrad manager."""
---> 28     cxn = backend.connect(host=host, port=port, name=name, **kw)
     29     return client.Client(cxn)
     30

C:\Code\pylabrad\labrad\backend.pyc in connect(host, port, name, backend, **kw)
    419             backend = 'asyncore'
    420     cxn = backends[backend](name)
--> 421     cxn.connect(host, port, **kw)
    422     return cxn
    423

C:\Code\pylabrad\labrad\backend.pyc in connect(self, host, port, timeout, passwo
rd)
     33         self.host = host
     34         self.port = port
---> 35         self.ID = self._connect(password, timeout)
     36         self.connected = True
     37

C:\Code\pylabrad\labrad\backend.pyc in _connect(self, password, _timeout)
     62         def _connect(self, password, _timeout):
     63             startReactor()
---> 64             self.cxn = self.call(getConnection, self.host, self.port, se
lf.name, password).wait()
     65             return self.cxn.ID
     66

C:\Code\pylabrad\labrad\backend.pyc in wait(self)
    396                 # If any Future in the queue fails,
    397                 # we immediately bail.
--> 398                 result.raiseException()
    399             else:
    400                 for func, args, kw in f.callbacks:

C:\Python279\lib\site-packages\twisted\python\failure.pyc in raiseException(self
)

Error: (2) Expected STARTTLS [payload=None]

In [3]:
```

**Comment by ejeffrey** [comment]
Hi Jim, can you use the older version for now?  That has encryption support
that isn't mergered into pylabrad yet.

Matthew: should we make the default 'optional' until we get everything
supported?

Evan

**Comment by maffoo** [comment]
@jwenner, as @ejeffrey said, we have not yet merged tls support into
pylabrad. In the meantime you can start the manager with the option
`--tls-required=false` to allow older clients to connect. We'll need to
enable this for a while until all the clients are updated, including
getting suitable replacements for the Delphi tools.

I'm glad you're trying out the latest stuff. Where are you running this?

**Comment by jwenner** [comment]
Thanks! With the `--tls-required=false` option and scalabrad-0.5.0, I can connect from other computers. However, I still get the INFO messages as in #37 (but not as frequent). I thus followed your advice here and in #37 to downgrade to 0.4.1.

I'm running this on rottmayer (the DAC testing computer in the ADR lab) so that I can figure out the kinks in getting the new LabRAD stuff (w/ Direct Ethernet, Qubit Sequencer, Manager, etc.) running. This is so we can move to current setup on Ivan (Dry DR) as soon as Anthony/Andrew start warming it up (likely early next week). Anything else I should know?

**Comment by ejeffrey** [comment]
Maybe we can make an SSL proxy / wrapper to let the registry editor /
grapher function until the replacements are complete.

**Comment by maffoo** [comment]
@jwenner, I don't think there's anything else you need to know, but please keep me in the loop as you're updating Ivan. I think the manager and servers on that fridge are reasonably current, it's the client code that people have been using on that fridge that is going to need a lot of work to bring up to date.
