### ISSUE TITLE
Cannot connect to LabRAD

### ISSUE THREAD

**Issue by DanielSank** [maffoo/scalabrad#44]
We have installed LabRAD on a new centOS 7 computer using an ansible script provided by @ejeffrey. While we can connect to the manager from the local machine (using pylabrad and Twisted version 15.4.0), we are unable to connect from any other machines in our department building.

If we try

``` python
cxn = labrad.connect(host='<computer_name>.physics.ucsb.edu')
```

from Windows with Twisted version 14.0.0, we get a an error from Twisted saying that there was a TCP time out. If we try the same thing on an Ubuntu machine with Twisted version 13.2.0 or 15.4.0 (the same version as on the host machine) we get "no route to host".

In trying to understand what's going on, I ran `netstat -an | grep 7682` and got the following output (added first line by hand to help understand what the columns mean):

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp6       0      0 :::7682                 :::*                    LISTEN     
tcp6       0      0 127.0.0.1:39472         127.0.0.1:7682          ESTABLISHED
tcp6       0      0 127.0.0.1:39471         127.0.0.1:7682          ESTABLISHED
tcp6       0      0 127.0.0.1:7682          127.0.0.1:39471         ESTABLISHED
tcp6       0      0 127.0.0.1:7682          127.0.0.1:39472         ESTABLISHED
```

At this point, the only concrete question I can ask is "what's going on?". This may come down to a question about the ansible script, but I sort of doubt it, because it seems the manager is running and listening for incoming connections.

**Comment by DanielSank** [comment]
If this is a firewall problem it's going to take me a loooong time to figure it out. Help appreciated there.

**Comment by jwenner** [comment]
@DanielSank, two recent issues I had that are potentially related are:
1. Error message "Expected STARTTLS" - #36
2. Error message "Exception: Connection lost." - labrad/pylabrad#186

Some questions which may be useful in the diagnosis:
1. Which pylabrad commit are you running (on all affected computers)?
2. When you run the scalabrad manager, what is the full command you are using? (Particularly any flags used)
3. Can you figure out which scalabrad version you are running? If running from the source, which commit? If from bintray, try looking in the following locations:
   
   a. Full directory where the manager is located (should be SCALABRAD/bin/labrad); look in the last folder of SCALABRAD.
   b. SCALABRAD/lib/scalabrad_2.11-xxx.jar. Please provide xxx (e.g., 0.5.1, 0.4.0, etc.)

**Comment by DanielSank** [comment]
Here's a copypasta from the ansible script which started the manager

```
[Unit]
Description=Labrad Manager

[Service]
ExecStartPre=mkdir -p /var/run/labrad
ExecStart={{ lrdir }}/scalabrad/bin/labrad --password {{ lrpass }} --registry file:///var/lib/labrad/registry.sqlite --tls-required false
Restart=always
RestartSec=5s
User=labrad
Environment=LABRADNODE={{ nodename }}
Environment=PYTHONPATH={{ lrdir }}/pylabrad:{{ lrdir }}
Environment=LABRADPASSWORD={{ lrpass }}

[Install]
WantedBy=multi-user.target
```

I'm guessing the `--tls-required false` is relevant, but not sure.

**Comment by DanielSank** [comment]
> 1. Which pylabrad commit are you running (on all affected computers)?

On the client machine: 88606135acf01e03e2df924ab2cd7a37a0762149. I'm not sure how the pylabrad version on the manager is relevant.

> 1. When you run the scalabrad manager, what is the full command you are using? (Particularly any flags used)

See previous post.

> 1. Can you figure out which scalabrad version you are running? If running from the source, which commit?

0.5.1

**Comment by DanielSank** [comment]
This was a firewall problem. The solution was to open tcp on 7682.

Thank you, @ejeffrey.
