### ISSUE TITLE
Unable to read password from environment variable

### ISSUE THREAD

**Issue by jwenner** [maffoo/scalabrad#46]
On the manager computer, we (myself and @cjneill) were unable to connect to the scalabrad manager unless we specified the password even though the LabRADPassword environment variable was set.

In particular, LabRADPassword was set to some value (say, PASSWORD). When we tried opening the manager in the usual way (not using the `--password` flag) and then tried `labrad.connect()` on the same computer, we got an error message about an incorrect password.

To get the manager/client working, we had to call the manager using the `--password=PASSWORD` flag and have the environment variable set (for Python clients).

**Comment by maffoo** [comment]
Please specify the environment variable as all caps `LABRADPASSWORD`.

**Comment by jwenner** [comment]
I'll let @cjneill try this out (as it's his manager computer). However, shouldn't it be possible to make this not case-sensitive?

**Comment by maffoo** [comment]
It's possible to make this case-insensitive, but I would prefer not to.

**Comment by DanielSank** [comment]
+1 for requiring all caps.
