### ISSUE TITLE
How do we control the manager?

### ISSUE THREAD

**Issue by DanielSank** [maffoo/scalabrad#5]
I seem to recall there was a web interface. Is this started automatically? If so, how is it accessed?

**Comment by maffoo** [comment]
the web interface, such as it is at the moment, is in a different repository: https://github.com/maffoo/scalabrad-web

You can check that out, then just type `sbt client/compile server/run` and it will come up on localhost:9000. The `client/compile` step is slow, but you only need to run it once. On subsequent launches you can just run `sbt server/run`

**Comment by DanielSank** [comment]
At the moment this leads to an unresolved dependency error for `com.typesafe#jse_2.10;1.0.0`, `com.typesafe#npm_2.10;1.0.0`, and `com.typesafe#webdriver_2.10;1.0.0`.
Some googling finds that there have been problems with typesafe resolution in the past, although I haven't found anything recent. @maffoo suggested this might be a temporary service problem, but given the history of issues with typesafe I'm not certain.

**Comment by maffoo** [comment]
It looks like typesafe have started to be better citizens and upload their stuff to maven central: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.typesafe%22%20AND%20a%3A%22jse_2.10%22
But I only see versions `1.1.0` and later there, so it's probably trying to go to typesafe's own repo to find the older versions. Can you post more of the error message you're seeing in sbt? In particular, there should be a section where it printed out all the repos it consulted when looking for the package before it failed to find anything.

**Comment by maffoo** [comment]
The web interface now lives at http://github.com/labrad/scalabrad-web. Closing this since the resolver issues have been fixed in that repo and fresh clones work.
