### ISSUE TITLE
TLS error results dropped connection

### ISSUE THREAD

**Issue by zchen088** [maffoo/scalabrad#50]
When we were setting up a new server computer and did not know the proper command line arguments to run the `labrad.bat` file, attempting `cxn = labrad.connect()` would first query:
`Accept server certificate for host 'mrfreeze.physics.ucsb.edu'? (accept just thi
s [O]nce; [S]ave and always accept this cert; [R]eject)` 

but then immediately drop the connection after input without any other error message.

**Comment by maffoo** [comment]
The lack of good error message in this case is a pylabrad problem. Can you open an issue there instead?
