### ISSUE TITLE
Why is the messager constructed lazily in the Hub class?

### ISSUE THREAD

**Issue by DanielSank** [maffoo/scalabrad#53]
What's the point of [this line](https://github.com/labrad/scalabrad/blob/master/src/main/scala/org/labrad/manager/Hub.scala#L54) using a lazy?

**Comment by maffoo** [comment]
This is to deal with the fact that Hub and Messager both want references to each other. We create the hub first, giving it a function to get the Messager reference, but when the Hub constructor runs the Messager has not actually been created yet, so we use lazy to ensure that we don't try to get the reference until later when we really need it.

**Comment by maffoo** [comment]
Closing for now. @DanielSank, please reopen if you have other questions.
