### ISSUE TITLE
Need way to kill server/client connection

### ISSUE THREAD

**Issue by ejeffrey** [maffoo/scalabrad#62]
The Delphi manager allows you to kill an unwanted connection from the GUI.  There doesn't seem to be any way to do that now.

**Comment by maffoo** [comment]
There is a `close_connection` setting on the manager that lets you kill a connection by id. It's not currently exposed in the web interface, but you can get at it from python, say. You can also use the `connection_info` setting to get info about active connections, including the connection id which you need to pass to `close_connection`.

**Comment by ejeffrey** [comment]
OK, opened bug on scalabrad-web.

**Comment by ejeffrey** [comment]
Actually, reopening...

The doc string for connection_info is

```
LabRAD Setting: "Manager" >> "Connection Info" (ID=10000)

Get information about connected servers and clients.

Accepts:
    _

Returns:
    *(wsbwwwwww)
```

that type tag needs to be documented...
