### ISSUE TITLE
how to compile the scala project?

### ISSUE THREAD

**Issue by ypzhong** [maffoo/scalabrad#68]
@maffoo  Hi Matthew, I'm trying to use the new version labRAD, although there is binary version available online, I want to make some slight modification and compile the source code myself, however it seems that it is a little tricky to properly set up everything to successfully compile it, do you have any suggestions? Any help will be sincerely appreciated. Thanks.

Best,
Youpeng

**Comment by maffoo** [comment]
Hi @ypzhong, the code is built using [sbt](http://www.scala-sbt.org/), a built tool for scala. The website for sbt has instructions on how to install it for various platforms. Once you have it set up you should be able to cd into the directory where you checked out scalabrad and run `sbt` in a terminal. That will drop you into an interactive sbt console where you can run various build commands, for example `compile` to compile, `test` to run tests, `pack` to build runnable code including start scripts for various platforms, and `packArchive` to build a distributable archive like what is on github. Hopefully that will get you started, but let me know if you have more questions.

**Comment by ypzhong** [comment]
Hi @maffoo  I see. It's amazing that it turns out to be so easy. I thought it would be very complicated. Anyway thank you very much. labRAD is becoming more and more fancy now!
