### ISSUE TITLE
Manger just... died.

### ISSUE THREAD

**Issue by pomalley** [maffoo/scalabrad#8]
Not really sure why but the scalabrad manager on redheatdos just shut down. The window it was running in closed, so I don't know why. I don't really have anything helpful to say about it, so... there's that.

**Comment by pomalley** [comment]
Changed title from "dies" to "died" because it's only happened once so far.

**Comment by maffoo** [comment]
Given that this only happened once in the era of redheatdos randomly putting network cards to sleep and we don't have any other actionable details, I'm going to close this. @pomalley, feel free to reopen if this reoccurs and you have more info about what might have happened.
